Watching for file changes with StatReloader
Watching for file changes with StatReloader
HTTP OPTIONS /api/accounts/user/ 200 [0.01, 192.168.65.1:60771]
Unauthorized: /api/accounts/user/
HTTP GET /api/accounts/user/ 401 [0.02, 192.168.65.1:60772]
Unauthorized: /api/accounts/user/
HTTP GET /api/accounts/user/ 401 [0.01, 192.168.65.1:60772]
Unauthorized: /api/accounts/user/
HTTP GET /api/accounts/user/ 401 [0.01, 192.168.65.1:60772]
HTTP OPTIONS /api/accounts/login/ 200 [0.01, 192.168.65.1:60771]
Bad Request: /api/accounts/login/
HTTP POST /api/accounts/login/ 400 [0.19, 192.168.65.1:60772]
HTTP OPTIONS /api/accounts/create/ 200 [0.01, 192.168.65.1:60771]
HTTP POST /api/accounts/create/ 201 [0.19, 192.168.65.1:60772]
HTTP POST /api/accounts/login/ 200 [0.20, 192.168.65.1:60772]
HTTP OPTIONS /api/scraper/scraping-tasks/ 200 [0.00, 192.168.65.1:60771]
HTTP GET /api/scraper/scraping-tasks/ 200 [0.01, 192.168.65.1:60772]
HTTP OPTIONS /api/scraper/generate/ 200 [0.00, 192.168.65.1:60771]
HTTP POST /api/scraper/generate/ 201 [0.02, 192.168.65.1:60772]
HTTP GET /api/scraper/scraping-tasks/ 200 [0.04, 192.168.65.1:60772]
HTTP OPTIONS /api/scraper/tasks/1/ 200 [0.00, 192.168.65.1:60776]
HTTP GET /api/scraper/tasks/1/ 200 [0.01, 192.168.65.1:60777]
HTTP GET /api/scraper/scraping-tasks/ 200 [0.02, 192.168.65.1:60777]
Watching for file changes with StatReloader
Watching for file changes with StatReloader
HTTP GET /api/scraper/scraping-tasks/ 200 [0.03, 192.168.65.1:61371]
Watching for file changes with StatReloader
HTTP GET /api/scraper/scraping-tasks/ 200 [0.04, 192.168.65.1:62005]
Watching for file changes with StatReloader
HTTP GET /api/scraper/scraping-tasks/ 200 [0.12, 192.168.65.1:62355]
HTTP GET /api/scraper/scraping-tasks/ 200 [0.03, 192.168.65.1:62470]
HTTP GET /api/scraper/tasks/1/ 200 [0.02, 192.168.65.1:62470]
HTTP GET /api/scraper/scraping-tasks/ 200 [0.02, 192.168.65.1:63095]
Watching for file changes with StatReloader
HTTP GET /api/scraper/scraping-tasks/ 200 [0.14, 192.168.65.1:63478]
HTTP GET /api/scraper/scraping-tasks/ 200 [0.03, 192.168.65.1:63478]
HTTP GET /api/scraper/scraping-tasks/ 200 [0.03, 192.168.65.1:63478]
HTTP GET /api/scraper/tasks/1/ 200 [0.03, 192.168.65.1:63478]
HTTP GET /api/scraper/scraping-tasks/ 200 [0.03, 192.168.65.1:63795]
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
HTTP GET /api/scraper/scraping-tasks/ 200 [0.03, 192.168.65.1:48085]
Watching for file changes with StatReloader
HTTP GET /api/scraper/scraping-tasks/ 200 [0.05, 192.168.65.1:48250]
HTTP GET /api/scraper/scraping-tasks/ 200 [0.02, 192.168.65.1:48619]
Watching for file changes with StatReloader
HTTP GET /api/scraper/scraping-tasks/ 200 [0.05, 192.168.65.1:48719]
HTTP GET /api/scraper/scraping-tasks/ 200 [0.03, 192.168.65.1:48719]
HTTP GET /api/scraper/scraping-tasks/ 200 [0.02, 192.168.65.1:48719]
HTTP POST /api/scraper/generate/ 201 [0.03, 192.168.65.1:49025]
HTTP GET /api/scraper/scraping-tasks/ 200 [0.04, 192.168.65.1:49025]
HTTP GET /api/scraper/scraping-tasks/ 200 [0.04, 192.168.65.1:49406]
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/usr/src/app/lead_generator/lead_generator/settings.py changed, reloading.
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py", line 275, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/postgresql/base.py", line 277, in get_new_connection
    connection = self.Database.connect(**conn_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.11/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/daphne/management/commands/runserver.py", line 97, in inner_run
    self.check_migrations()
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 581, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/migrations/loader.py", line 58, in __init__
    self.build_graph()
  File "/usr/local/lib/python3.11/site-packages/django/db/migrations/loader.py", line 235, in build_graph
    self.applied_migrations = recorder.applied_migrations()
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/migrations/recorder.py", line 89, in applied_migrations
    if self.has_table():
       ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/migrations/recorder.py", line 63, in has_table
    with self.connection.cursor() as cursor:
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py", line 316, in cursor
    return self._cursor()
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py", line 292, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py", line 274, in ensure_connection
    with self.wrap_database_errors:
  File "/usr/local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py", line 275, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/postgresql/base.py", line 277, in get_new_connection
    connection = self.Database.connect(**conn_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

/usr/src/app/lead_generator/lead_generator/settings.py changed, reloading.
Watching for file changes with StatReloader
HTTP OPTIONS /api/accounts/login/ 200 [0.02, 192.168.65.1:18151]
HTTP POST /api/accounts/login/ 200 [0.49, 192.168.65.1:18152]
HTTP OPTIONS /api/scraper/scraping-tasks/ 200 [0.01, 192.168.65.1:18151]
HTTP GET /api/scraper/scraping-tasks/ 200 [0.02, 192.168.65.1:18152]
/usr/src/app/lead_generator/scraper/views.py changed, reloading.
Watching for file changes with StatReloader
/usr/src/app/lead_generator/scraper/views.py changed, reloading.
Watching for file changes with StatReloader
HTTP GET /api/scraper/scraping-tasks/ 200 [0.05, 192.168.65.1:18153]
HTTP GET /api/scraper/scraping-tasks/ 200 [0.04, 192.168.65.1:18153]
HTTP OPTIONS /api/scraper/tasks/2/ 200 [0.01, 192.168.65.1:18154]
HTTP GET /api/scraper/tasks/2/ 200 [0.03, 192.168.65.1:18153]
HTTP OPTIONS /api/scraper/generate/ 200 [0.01, 192.168.65.1:18154]
HTTP POST /api/scraper/generate/ 201 [0.03, 192.168.65.1:18153]
HTTP GET /api/scraper/scraping-tasks/ 200 [0.04, 192.168.65.1:18153]
Watching for file changes with StatReloader
Watching for file changes with StatReloader
HTTP GET /api/scraper/scraping-tasks/ 200 [0.03, 192.168.65.1:18277]
HTTP GET /api/scraper/scraping-tasks/ 200 [0.04, 192.168.65.1:18290]
HTTP GET /api/scraper/scraping-tasks/ 200 [0.02, 192.168.65.1:18291]
Watching for file changes with StatReloader
Watching for file changes with StatReloader
HTTP GET /api/scraper/scraping-tasks/ 200 [0.06, 192.168.65.1:18416]
HTTP OPTIONS /api/scraper/tasks/3/ 200 [0.01, 192.168.65.1:18417]
HTTP GET /api/scraper/tasks/3/ 200 [0.02, 192.168.65.1:18416]
HTTP GET /api/scraper/scraping-tasks/ 200 [0.03, 192.168.65.1:18430]
